### ISSUE TITLE
Migrate from npm to yarn

### ISSUE THREAD

**Issue by mariodedapolito** [arol-polito/AROL-CLOUD#6]
Migrate both BE and FE from npm to yarn

**Comment by gmacario** [comment]
@mariodedapolito understood.

I was asking since I have little experience with Yarn and in all our projects at https://github.com/arolgroup we have not had any need to move away from npm.

Anyway if you feel that Yarn provides more value to this project please go ahead with this feature. Just make sure that npm can still be used as an alternative (as an example, keep package-lock.json in sync). If this is not manageable, I advise to document it clearly in the README.md

**Comment by gmacario** [comment]
> yarn will help us remove the `--force` from the `npm install`

Where is this needed in the codebase?

**Comment by mariodedapolito** [comment]
@gmacario I do agree. We can keep npm for the moment, the move to yarn is not mandatory, so if we keep consistency with other AROL project, better to stick with npm.
We need the `npm install --force` for the FE as the library which we are using for some dashboard gauges is creating some conflicts with other deps. I will try to find a workaround for this problem and keep using npm.

**Comment by gmacario** [comment]
> We need the `npm install --force` for the FE as the library which we are using for some dashboard gauges is creating some conflicts with other deps. I will try to find a workaround for this problem and keep using npm.

Excellent. I just created https://github.com/arol-polito/AROL-CLOUD/issues/8 to track that. Please feel free to expand the description
